config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :recurring_tasks, except: [:index]

app/models/recurring_task.rb
class RecurringTask < ActiveRecord::Base
  UnauthorizedError = Class.new(StandardError)

  belongs_to :issue
  belongs_to :tracker

  validates :issue_id,    presence: true, uniqueness: true
  validates :tracker_id,  presence: true

  validates :time, presence: true

  DAYS = %w(monday tuesday wednesday thursday friday saturday sunday).freeze

  RUN_TYPE_W_DAYS = :week_days
  RUN_TYPE_M_DAYS = :month_days

  attr_accessor :client_run_type

  before_save do
    if client_run_type.present?
      if client_run_type == RUN_TYPE_M_DAYS.to_s
        DAYS.each{|d| public_send("#{d}=", false)}
      else
        self.month_days = []
      end
    end
  end

  # @return [Array<String>] array of days when schedule should be executed
  def days
    DAYS.select{|d| public_send(d)}
  end

  def months=(value)
    value ||= default_months
    super(value.to_json)
  end

  def months
    result = super
    JSON.parse(result)
  rescue
    raise result
  end

  def month_days=(value)
    value ||= default_month_days
    super(value.to_json)
  end

  def time=(value)
    value = Time.new(*value.values) if value.is_a?(Hash)

    return super(value.to_time) unless value.respond_to?(:utc)
    super(value.dup.utc)
  end

  def time
    super&.localtime
  end

  def month_days
    result = super
    result = JSON.parse(result)
  rescue
    raise result
  end

  def month_days_parsed
    month_days.map{|x| x == 'last_day' ? Time.now.end_of_month.day.to_s : x}.compact.uniq
  end

  def self.schedules(current_time = Time.now)
    week_day  = current_time.strftime('%A').downcase
    month_day = current_time.day

    # months
    scope = where("months LIKE '%\"#{current_time.month.to_s}\"%'")

    scope.select do |schedule|
      if schedule.month_days.empty?
        # week day
        next unless schedule.public_send(week_day)
      else
        # month day
        month_days = schedule.month_days_parsed
        next unless month_days.include?(month_day.to_s)
      end

      # time
      schedule.time_came?(current_time)
    end
  end

  # @return [Issue] copied issue
  def copy_issue(associations = [])
    return if issue.project.archived? || issue.project.closed?

    settings = Setting.find_by(name: :plugin_redmine_recurring_tasks)&.value || {}

    issue.deep_clone(include: associations, except: %i[parent_id root_id lft rgt created_on updated_on closed_on]) do |original, copy|
      case original
      when Issue
        copy.init_journal(original.author)
        new_author =
          if settings['use_anonymous_user']
            User.anonymous
          else
            unless original.author.allowed_to?(:copy_issues, issue.project)
              raise UnauthorizedError, "User #{original.author.name} (##{original.author.id}) unauthorized to copy issues"
            end
            original.author
          end
        copy.custom_field_values = original.custom_field_values.inject({}) { |h, v| h[v.custom_field_id] = v.value; h }
        copy.author_id = new_author.id
        copy.tracker_id = original.tracker_id
        copy.parent_issue_id = original.parent_id
        copy.status_id =
          case settings['copied_issue_status']
          when nil
            copy.new_statuses_allowed_to(original.author).sort_by(&:position).first&.id
          when '0'
            original.status_id
          else
            settings['copied_issue_status']
          end
        copy.attachments = original.attachments.map do |attachement|
          attachement.copy(container: original)
        end
        copy.watcher_user_ids = original.watcher_users.select { |u| u.status == User::STATUS_ACTIVE }.map(&:id)

        copy.start_date = Time.now

        if original.due_date.present?
          issue_date = (original.start_date || original.created_on).to_date
          copy.due_date = copy.start_date + (original.due_date - issue_date)
        end
      else
        next
      end
    end.tap(&:save!)
  end

  # @return [Boolean] boolean result of copy issue and save of schedule last try timestamp
  def execute(associations = nil)
    self.last_try_at = Time.now
    copy_issue(associations) && save
  end

  # @return [Symbol] return :month_days if any month days are present, else :week_days
  def run_type
    self.month_days.any? ? RUN_TYPE_M_DAYS : RUN_TYPE_W_DAYS
  end

  def time_came?(current_time = Time.now)
    utc_offset = current_time.utc_offset / 60 / 60
    utc_offset -= 1 if time.in_time_zone(utc_offset).dst?
    time.in_time_zone(utc_offset).strftime('%H%M%S').to_i <= current_time.strftime('%H%M%S').to_i &&
      (last_try_at.nil? || last_try_at.in_time_zone(utc_offset).strftime('%Y%m%d').to_i < current_time.strftime('%Y%m%d').to_i)
  end

  private

  def default_month_days
    []
  end

  def default_months
    (1..12).to_a.map(&:to_s)
  end
end

app/controllers/recurring_tasks_controller.rb
class RecurringTasksController < ApplicationController
  before_action :set_schedule, only: [:edit, :destroy, :update]
  before_action :set_issue
  before_action :check_permission

  def new
    existing_schedule = RecurringTask.find_by(issue: @issue)
    if existing_schedule
      return redirect_to edit_recurring_task_path(existing_schedule)
    end

    @schedule = RecurringTask.new(tracker: @issue.tracker, issue: @issue)
  end

  def create
    @schedule = RecurringTask.new
    @schedule.issue = @issue
    @schedule.assign_attributes(recurring_task_params)
    if @schedule.save
      redirect_to issue_path(@issue)
    else
      render :new
    end
  end

  def update
    @schedule.assign_attributes(recurring_task_params)
    if @schedule.save
      redirect_to issue_path(@issue)
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @schedule.destroy
    redirect_to issue_path(@issue)
  end

  private

  def recurring_task_params
    params.require(:recurring_task).permit(:sunday, :monday, :tuesday, :wednesday,
                                           :thursday, :friday, :saturday, :time, :tracker_id, :client_run_type,
                                           months: [], month_days: [])
  end

  def set_schedule
    @schedule = RecurringTask.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def set_issue
    if @schedule.present?
      @issue = @schedule.issue
    else
      @issue = Issue.find(params[:issue_id])
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def check_permission
    unless User.current.allowed_to?(:manage_schedule, @issue.project)
      raise ::Unauthorized
    end
  end
end

app/helpers/recurring_tasks_helper.rb
module RecurringTasksHelper
  def month_names
    standalone_key = 'date.standalone_month_names'
    I18n.exists?(standalone_key) ? I18n.t(standalone_key) : I18n.t('date.month_names')
  end
end

app/views/recurring_tasks/_form.html.erb
<%= form_for @schedule, html: {id: 'recurring_task_form'} do |f| %>
  <div class="box">
    <fieldset class="box tabular"><legend><%= @schedule.issue.subject %></legend>
      <input type="hidden" name="issue_id" value="<%= @schedule.issue.id %>">

      <%= error_messages_for 'schedule' %>

      <style>
        table.weekly-schedule {
          width: 100%;
        }
      </style>

      <script>
        $(document).ready(function() {
          processOption();
        });

        $(document).on('change', 'input[name="recurring_task[client_run_type]"]', function() {
          processOption();
        });

        function processOption() {
          var isMonthDays = $("input[name='recurring_task[client_run_type]']:checked").val().toString() == 'month_days';

          if (isMonthDays) {
            $('#month_days').prop('disabled', false);
            $('input[type="checkbox"].week_day').prop('checked', false);
            $('input[type="checkbox"].week_day').prop('disabled', true);
          } else {
            $('#month_days').prop('disabled', true);
            $('#month_days option').prop('selected', false);
            $('input[type="checkbox"].week_day').prop('disabled', false);
          }
        }
      </script>

      <table class="weekly-schedule">
        <tr>
          <td valign="top" width="20%">
            <p>
              <label>
                <%= RecurringTask.human_attribute_name(:tracker) %>
                <%= f.collection_select(:tracker_id, Tracker.all, :id, :name) %>
              </label>
            </p>

            <p>
              <label>
                <%= RecurringTask.human_attribute_name(:time) %>
                <%= f.time_select :time, minute_step: 5 %>
              </label>
              (<%= Time.now.zone %>)
            </p>
          </td>

          <td valign="top" width="30%">
            <p>
              <label>
                <%= l('month') %>

                <% month_names.compact.each_with_index do |m, index| %>
                <% i = index + 1 %>
                <p>
                  <label>
                    <%= m %>
                    <%= check_box_tag 'recurring_task[months][]', i, @schedule.months.include?(i.to_s) %>
                  </label>
                </p>
                <% end %>
              </label>
            </p>
          </td>

          <td valign="top" width="60%">
            <div><%= l('note') %><br><br></div>

            <fieldset class="box tabular">
              <div style="float: left; margin-left: 5em;">
                <p>
                  <label>
                    <input type="radio" name="recurring_task[client_run_type]"
                           value="<%= RecurringTask::RUN_TYPE_M_DAYS %>"<%= ' checked' if @schedule.run_type == RecurringTask::RUN_TYPE_M_DAYS %>> <%= l('month_day') %>
                  </label>
                </p>
                <p>
                  <label>
                    <select id="month_days" name="recurring_task[month_days][]" multiple style="width: 500px; height: 450px;">
                      <% 1.upto(31) do |i| %>
                        <option value="<%= i %>"<%= ' selected' if @schedule.month_days.include?(i.to_s) %>>
                          <%= i %>
                        </option>
                      <% end %>
                      <option value="last_day"<%= ' selected' if @schedule.month_days.include?('last_day') %>>
                        <%= l('last_day') %>
                      </option>
                    </select>
                  </label>
                  <br>
                </p>
              </div>

              <div style="float: left;">
                <p>
                  <label>
                    <input type="radio" name="recurring_task[client_run_type]"
                           value="<%= RecurringTask::RUN_TYPE_W_DAYS %>"<%= ' checked' if @schedule.run_type == RecurringTask::RUN_TYPE_W_DAYS %>> <%= l('week_day') %>
                  </label>
                </p>

                <p>
                  <label>
                    <%= RecurringTask.human_attribute_name(:monday) %>
                    <%= f.check_box :monday, class: 'week_day' %>
                  </label>
                </p>

                <p>
                  <label>
                    <%= RecurringTask.human_attribute_name(:tuesday) %>
                    <%= f.check_box :tuesday, class: 'week_day' %>
                  </label>
                </p>

                <p>
                  <label>
                    <%= RecurringTask.human_attribute_name(:wednesday) %>
                    <%= f.check_box :wednesday, class: 'week_day' %>
                  </label>
                </p>

                <p>
                  <label>
                    <%= RecurringTask.human_attribute_name(:thursday) %>
                    <%= f.check_box :thursday, class: 'week_day' %>
                  </label>
                </p>

                <p>
                  <label>
                    <%= RecurringTask.human_attribute_name(:friday) %>
                    <%= f.check_box :friday, class: 'week_day' %>
                  </label>
                </p>

                <p>
                  <label>
                    <%= RecurringTask.human_attribute_name(:saturday) %>
                    <%= f.check_box :saturday, class: 'week_day' %>
                  </label>
                </p>

                <p>
                  <label>
                    <%= RecurringTask.human_attribute_name(:sunday) %>
                    <%= f.check_box :sunday, class: 'week_day' %>
                  </label>
                </p>
              </div>
            </fieldset>
          </td>
        </tr>
      </table>
    </fieldset>
  </div>

  <div>
    <%= f.submit ( f.object.new_record? ? l(:button_add) : l(:button_change)) %>

    <% if @schedule.persisted? %><%= link_to(l(:button_delete), recurring_task_path(@schedule), method: :delete, data: {confirm: l(:text_are_you_sure)}) %> |
    <% end %>

    <%= link_to(l(:button_cancel), issue_path(@issue)) %>
  </div>
<% end %>

app/views/recurring_tasks/edit.html.erb
<h2><%= l(:project_module_redmine_recurring_tasks) %></h2>

<%= render partial: 'form' %>

app/views/recurring_tasks/issues/_bottom.html.erb
<% if controller_name == 'issues' && action_name == 'show' && User.current.allowed_to?(:view_schedule, @project) %>

<hr />

<div class="redmine_recurring_tasks">
  <% if User.current.allowed_to?(:manage_schedule, @project) && (@issue.recurring_task_root.nil? || @issue.recurring_task_root.issue == @issue) %>
    <div class="contextual">
      <% if @issue.recurring_task.present? %>
        <a href="<%= edit_recurring_task_path(@issue.recurring_task_root.id) %>"><%= l(:button_change) %></a>
      <% else %>
        <a href="<%= new_recurring_task_path(issue_id: @issue.id) %>"><%= l(:button_add) %></a>
      <% end %>
    </div>
  <% end %>

  <% RedmineRecurringTasks::IssuePresenter.new(@issue).tap do |issue| %>
    <p><strong><%= l(:schedule) %></strong></p>
    <%= issue.schedule %>
    <%= issue.schedule_template %>
  <% end %>
</div>
<% end %>

app/views/recurring_tasks/new.html.erb
<h2><%= l(:project_module_redmine_recurring_tasks) %></h2>

<%= render partial: 'form' %>

app/views/settings/_redmine_recurring_tasks.html.erb
<%
  @settings = ActionController::Parameters.new(@settings)
%>
<p>
  <%= label_tag 'settings[associations]', l(:settings_associations) %>
  <%= select_tag 'settings[associations]',
                 options_for_select(RedmineRecurringTasks.issue_associations, @settings[:associations]),
                 { multiple: true, size: 20, style: 'width: 50%;' } %>
  <p class="notice"><%= l(:settings_associations_warning) %></p>
</p>
<p>
  <%= button_tag l(:button_reset), type: :button, onClick: '$("#settings_associations option:selected").prop("selected", false);' %>
</p>

<p>
  <%= label_tag 'settings[copied_issue_status]', l(:settings_copied_issue_status) %>
  <%= select_tag 'settings[copied_issue_status]',
                 options_for_select([[l(:settings_copy_from_original), 0], *IssueStatus.sorted.map { |status| [status.name, status.id] }], @settings[:copied_issue_status]),
                 include_blank: true %>
</p>
<p>
  <%= label_tag 'settings[use_anonymous_user]', l(:settings_use_anonymous_user) %>
  <%= check_box_tag 'settings[use_anonymous_user]', 1, @settings[:use_anonymous_user] %>
</p>